#ifndef CONFIG_H
#define CONFIG_H
#define DISABLE_JTAG

#define RGB_MATRIX_LED_COUNT 2
#define RGB_MATRIX_SLEEP true
#define RGB_MATRIX_DEFAULT_HUE 255
#define RGB_MATRIX_DEFAULT_SPD 30
#define ENABLE_RGB_MATRIX_BREATHING
#define ENABLE_RGB_MATRIX_CYCLE_ALL
#define ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#define ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_CYCLE_ALL

//#define TT Layer
#define TAPPING_TOGGLE 2

/* Bootmagic Lite key configuration */
#define BOOTMAGIC_LITE_ROW 0
#define BOOTMAGIC_LITE_COLUMN 0

//#define FORCE_NKRO
#define MIDI_ADVANCED
#endif
