#include QMK_KEYBOARD_H
#include "leds.c"

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(
		LT(5,KC_ESC), 	 KC_Q,    		    KC_W,             KC_E,           KC_R,          KC_T, 
		LT(4,KC_TAB), 	 KC_A,    		    KC_S,             KC_D,           KC_F,          KC_G, 
		LT(3,KC_DEL), 	 KC_Z,    		    KC_X,             KC_C,           KC_V,          KC_B, 
		LGUI_T(KC_QUOT), LALT_T(KC_SCLN), LSFT_T(KC_COMM),  LCTL_T(KC_DOT), LT(1, KC_SPC), LT(2, KC_ENT)), 

	[1] = LAYOUT( 
		KC_GRV,  KC_7,    KC_8,    KC_9,    KC_PDOT, KC_PLUS, 
		KC_LBRC, KC_4,    KC_5,    KC_6,    KC_0,    KC_MINS, 
		KC_RBRC, KC_1,    KC_2,    KC_3,    KC_BSPC, KC_PAST, 
		KC_BSLS, KC_UNDS, KC_QUES, KC_EQL,  TO(0),   KC_SLSH), 

	[2] = LAYOUT( 
		KC_MS_LEFT, KC_MS_UP,   KC_MS_RIGHT, KC_LEFT,       KC_UP,   KC_RGHT,     
		KC_MS_BTN1, KC_MS_DOWN, KC_MS_BTN2,  KC_MS_WH_UP,   KC_DOWN, KC_HOME, 
		KC_MS_BTN4, KC_MS_BTN5, KC_MS_BTN3,  KC_MS_WH_DOWN, KC_PGUP, KC_END, 
		KC_LGUI,    KC_LALT,    KC_LSFT,     KC_LCTL,       KC_PGDN, TO(0)), 

	[3] = LAYOUT( 
		XXXXXXX, XXXXXXX, KC_F9,   KC_F10,  KC_F11,  KC_F12, 
		XXXXXXX, XXXXXXX, KC_F5,   KC_F6,   KC_F7,   KC_F8,    
		TO(0),   XXXXXXX, KC_F1,   KC_F2,   KC_F3,   KC_F4,    
		KC_LGUI, KC_LALT, KC_LSFT, KC_LCTL, MO(6),   MO(7)), 

	[4] = LAYOUT( 
		KC_MYCM, KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,                       
		TO(0),   KC_H,    KC_J,    KC_K,    KC_L,    KC_DQUO ,                     
		KC_CALC, KC_N,    KC_M,    KC_LT,   KC_GT,   KC_COLN, 
		KC_RGUI, KC_RALT, KC_RSFT, KC_RCTL, XXXXXXX, KC_CAPS), 

	[5] = LAYOUT( 
		TO(0),   KC_MPLY, KC_MUTE, XXXXXXX, XXXXXXX, XXXXXXX, 
		TO(4),   KC_VOLD, KC_VOLU, XXXXXXX, XXXXXXX, XXXXXXX, 
		TO(3),   KC_MPRV, KC_MNXT, XXXXXXX, XXXXXXX, XXXXXXX, 
		KC_RGUI, KC_RALT, KC_RSFT, KC_RCTL, TO(1),   TO(2)), 

	[6] = LAYOUT( 
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, 
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, 
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, 
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX), 

	[7] = LAYOUT( 
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, 
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, 
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, 
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX), 

	[8] = LAYOUT( 
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, 
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, 
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, 
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX)
};
