#include QMK_KEYBOARD_H
#include <stdio.h>
#include "leds.c"

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT( //Alphabet
		KC_ESC, KC_Q, KC_W, KC_E, KC_R, KC_T,                   XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC, 
		KC_TAB, KC_A, KC_S, KC_D, KC_F, KC_G,                   XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_ENT, 
		KC_DEL, KC_Z, KC_X, KC_C, KC_V, KC_B,                   XXXXXXX, LGUI(KC_ESC),  KC_MPLY,XXXXXXX,       KC_N, KC_M, LT(3, KC_COMM), LT(4, KC_DOT), KC_SLSH, KC_DEL,
		KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, MO(1), KC_SPC,      LCTL(KC_C),LCTL(KC_X),  LCTL(KC_V),LCTL(KC_Z), KC_SPC, MO(2), KC_LEFT, KC_RGHT, KC_UP, KC_DOWN), 
                                                                                                  
	[1] = LAYOUT( //Number & Punctuation                                                            
		KC_TILD, KC_7, KC_8, KC_9, KC_PDOT, KC_PPLS,            XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      KC_PAST, KC_PERC, KC_LCBR, KC_RCBR, KC_AT, KC_UNDS,   
		KC_GRV, KC_4, KC_5, KC_6, KC_0, KC_MINS,                XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      KC_PIPE, KC_HASH, KC_LBRC, KC_RBRC, KC_QUOT, KC_DQUO,  
		KC_DLR, KC_1, KC_2, KC_3, KC_BSPC,KC_EQL,               XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      KC_BSLS, KC_AMPR,  KC_LPRN, KC_RPRN, KC_EXLM, KC_CIRC, 
		KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, TO(0), KC_PENT,     XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      XXXXXXX, LGUI(KC_SPC), XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX), 
                                                                                                           
	[2] = LAYOUT( //Punctuation & Arrow key                                                                  
		KC_PSCR, KC_INS, XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,			XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      KC_F9, KC_F10, KC_F11, KC_F12, KC_VOLD, KC_VOLU,           
		KC_SCRL, KC_NUM, XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      KC_F5, KC_F6, KC_F7, KC_F8, KC_MPRV, KC_MNXT,           
		KC_PAUS, KC_APP, RGB_TOG, XXXXXXX,XXXXXXX, XXXXXXX,			XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      KC_F1, KC_F2, KC_F3, KC_F4, KC_MPLY, KC_MUTE,           
		KC_RGUI, KC_LALT, KC_RCTL, KC_LSFT, KC_CAPS, XXXXXXX,   XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      XXXXXXX, TO(0), KC_HOME, KC_END, KC_PGUP, KC_PGDN),
                                                                                                           
	[3] = LAYOUT(                                                                                            
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX),
                                                                                                           
	[4] = LAYOUT( //Fn & Quickly Open File                                                                   
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX),
                                                                                                           
	[5] = LAYOUT(                                                                                            
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX),
                                                                                                           
	[6] = LAYOUT( //App hotkeys                                                                              
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX),
                                                                                                           
	[7] = LAYOUT( //QK_BOOT, PC On/Off & Quickly input                                                       
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX),
                                                                                                           
	[8] = LAYOUT( //R:Keypad                                                                                 
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX,XXXXXXX, XXXXXXX)
}; 

#if defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
    [0] = { ENCODER_CCW_CW(LGUI(KC_MINS), LGUI(KC_EQL)), ENCODER_CCW_CW(KC_VOLD, KC_VOLU) },
    [1] = { ENCODER_CCW_CW(LCTL(KC_MINS), LCTL(KC_PLUS)), ENCODER_CCW_CW(KC_MPRV, KC_MNXT) },
    [2] = { ENCODER_CCW_CW(LCTL(KC_MINS), LCTL(KC_PLUS)), ENCODER_CCW_CW(KC_MPRV, KC_MNXT) },
    [3] = { ENCODER_CCW_CW(KC_UP, KC_DOWN), ENCODER_CCW_CW(KC_LEFT, KC_RGHT) },
    [4] = { ENCODER_CCW_CW(KC_UP, KC_DOWN), ENCODER_CCW_CW(KC_LEFT, KC_RGHT) },
    [5] = { ENCODER_CCW_CW(KC_UP, KC_DOWN), ENCODER_CCW_CW(KC_LEFT, KC_RGHT) },
    [6] = { ENCODER_CCW_CW(KC_UP, KC_DOWN), ENCODER_CCW_CW(KC_LEFT, KC_RGHT) },
    [7] = { ENCODER_CCW_CW(KC_UP, KC_DOWN), ENCODER_CCW_CW(KC_LEFT, KC_RGHT) },
    [8] = { ENCODER_CCW_CW(KC_UP, KC_DOWN), ENCODER_CCW_CW(KC_LEFT, KC_RGHT) }
};
#endif
