#pragma once

#define USB_VBUS_PIN A10
#define WS2812_DI_PIN A9
#define SPLIT_HAND_PIN B7
#define SERIAL_USART_TX_PIN B6

/* RGBLIGHT configuration */
#define RGBLIGHT_LED_COUNT 2
#define RGBLED_MAP { 1, 0 }
#define RGBLED_SPLIT { 1, 1 }
#define RGBLIGHT_LAYERS
#define RGBLIGHT_MAX_LAYERS 9
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_CHRISTMAS
//#define RGBLIGHT_EFFECT_RAINBOW_SWIRL

#undef  SPLIT_USB_DETECT
